export const studentRecord = [
    {
        name: "Mark",
        contact: "3456789679",
        contact: "3456789679",
        course: "Diploma",
        session: "2020",
        city: "Jsr",
        state: "ghjk",
        admDate: "ghjk",
        verifyStatus: "verified",
    },
    {
        name: "Jacob",
        contact: "9087654678",
        contact: "9087654678",
        course: "mabesk",
        session: "2021",
        city: "Bangalore",
        state: "karnataka",
        admDate: "karnataka",
        verifyStatus: "verified",
    },
    {   
        name: "Larry the Bird",
        contact: "987654678",
        contact: "987654678",
        course: "ghjhj",
        session: "2020",
        city: "goa",
        state: "iujhg",
        admDate: "iujhg",
        verifyStatus: "verified",
    }
];